name = "interchat-web"
main = "worker.ts"
compatibility_date = "2025-12-31"
compatibility_flags = ["nodejs_compat"]
#account_id = "510ea6d43d5506ea7ba8abb4e852d091" # Azisaba Network
account_id = "25b0cbcd514595ee6804118b47fb7e30" # Acrylic Style

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "interchat"
database_name = "interchat"
#database_id = "6fd39615-0f51-4f3d-b363-ae2e382178a3" # Azisaba Network
database_id = "78a3fd28-694f-4b46-a411-f8912230bd2f" # Acrylic Style
remote = true

[durable_objects]
bindings = [{ name = "INTERCHAT_GUILD", class_name = "InterchatGuild" }]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["InterchatGuild"]

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
